"use client";
import React from "react";
import Head from "next/head";
import Link from "next/link";
import Banner from "@/components/home/banner/banner";
import Category from "@/components/home/category";
import Promo from "@/components/home/promo";
import Activity from "@/components/home/activity";
import Navbar from "@/components/home/navbar";
import Footer from "@/components/home/footer";

const index: React.FC = () => {
  return (
    <>
      <Head>
        <title>Destinify</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <div className="bg-[#fefffe] p-0 pt-0">
          <Navbar />
          <Banner />
          <Promo />
          <Activity />
          <Category />
          <Footer />
        </div>
      </div>
    </>
  );
};

export default index;
