"use client";
import React from "react";
import Head from "next/head";
import Link from "next/link";
import Banner from "@/components/Layout/Home/BannerLayout";
import Category from "@/components/Layout/Home/CategoryLayout";
import Promo from "@/components/Layout/Home/PromoLayout";
import Activity from "@/components/Layout/Home/ActivityLayout";
import Navbar from "@/components/Fragments/Home/Navbar";
import Footer from "@/components/Fragments/Home/Footer";
import Value from "@/components/Layout/Home/ValueLayout";
import About from "@/components/Layout/Home/AboutLayout";
import Booking from "@/components/Layout/Home/BookingLayout";

const index: React.FC = () => {
  return (
    <>
      <Head>
        <title>Destinify</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="bg-[#fefffe] ">
        <Navbar />
        <Banner />
        <div className="px-4 lg:px-16 pt-0">
          <Value />
          <Promo />
          <Activity />
          <About />
          <Category />
          <div className="hidden lg:block"></div>
          <Booking />
        </div>
        <Footer />
      </div>
    </>
  );
};

export default index;
